## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def configure(conf): 
    have_itpp = conf.pkg_check_modules('IT++', 'itpp', mandatory=True)
    conf.env['ENABLE_ITPP'] = have_itpp
    conf.report_optional_feature("IT++", "IT++ library",
                                 conf.env['ENABLE_ITPP'],
                                 "IT++ not found")
    if conf.env['ENABLE_ITPP']:
		conf.env.append_value('CXXFLAGS', '-DNO_INT_SIZE_CHECK')

def build(bld):
    obj = bld.create_ns3_module('physim-wifi', ['network', 'propagation','internet', 'config-store', 'tools', 'point-to-point', 'wifi', 'mobility', 'applications', 'csma'])
    obj.source = [
        'model/physim-blockinterleaver.cc',
        'model/physim-channel-estimator.cc',
        'model/physim-convolutional-encoder.cc',
        'model/physim-helper.cc',
        'model/physim-interference-helper.cc',
        'model/physim-ofdm-symbolcreator.cc',
        'model/physim-propagation-loss-model.cc',
        'model/physim-scrambler.cc',
        'model/physim-signal-detector.cc',
        'model/physim-signal-detector-opt.cc',
        'model/physim-vehicular-channel-spec.cc',
        'model/physim-vehicular-TDL-channel.cc',
        'model/physim-wifi-channel.cc',
        'model/physim-wifi-phy.cc',
        'model/physim-wifi-phy-state-helper.cc',
        'model/physim-wifi-phy-tag.cc',
        'helper/physim-wifi-helper.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'physim-wifi'
    headers.source = [
        'model/physim-blockinterleaver.h',
        'model/physim-channel-estimator.h',
        'model/physim-convolutional-encoder.h',
        'model/physim-helper.h',
        'model/physim-interference-helper.h',
        'model/physim-ofdm-symbolcreator.h',
        'model/physim-propagation-loss-model.h',
        'model/physim-scrambler.h',
        'model/physim-signal-detector.h',
        'model/physim-signal-detector-opt.h',
        'model/physim-vehicular-channel-spec.h',
        'model/physim-vehicular-TDL-channel.h',
        'model/physim-wifi-channel.h',
        'model/physim-wifi-phy.h',
        'model/physim-wifi-phy-state-helper.h',
        'model/physim-wifi-phy-tag.h',
        'helper/physim-wifi-helper.h',
        ]
        
    if (bld.env['ENABLE_EXAMPLES']):
    	bld.add_subdirs('example')
    
    if bld.env['ENABLE_ITPP']:
		obj.uselib = 'IT++'
		obj.env.append_value('CXXDEFINES', "ENABLE_ITPP")

